const scenarios = {
    demo: [
        ['direction', 'FORWARD'],
        ['status', 'POWER_ON'],
        ['set_speed', 6],
        ['wait', 10],
        ['set_speed', 10],
        ['wait', 10],
        ['set_speed', 0],
        ['status', 'POWER_OFF'],
        ['wait', 10],
        ['direction', 'BACKWARD'],
        ['status', 'POWER_ON'],
        ['set_speed', 6],
        ['wait', 10],
        ['set_speed', 10],
        ['wait', 10],
        ['set_speed', 0],
        ['status', 'POWER_OFF'],
        ['wait', 10]
    ],
    scenario_1: [
        ['direction', 'FORWARD'],
        ['status', 'POWER_ON'],
        ['set_speed', 6],
        ['wait', 10],
        ['set_speed', 8],
        ['wait', 10],
        ['set_speed', 10],
        ['wait', 10],
        ['set_speed', 12],
        ['wait', 100],
        ['set_speed', 10],
        ['wait', 10],
        ['set_speed', 8],
        ['wait', 10],
        ['set_speed', 6],
        ['wait', 10],
        ['set_speed', 0],
        ['status', 'POWER_OFF'],
        ['wait', 20],
        ['direction', 'BACKWARD'],
        ['status', 'POWER_ON'],
        ['set_speed', 6],
        ['wait', 10],
        ['set_speed', 8],
        ['wait', 10],
        ['set_speed', 10],
        ['wait', 10],
        ['set_speed', 12],
        ['wait', 100],
        ['set_speed', 10],
        ['wait', 10],
        ['set_speed', 8],
        ['wait', 10],
        ['set_speed', 6],
        ['wait', 10],
        ['set_speed', 0],
        ['status', 'POWER_OFF'],
        ['wait', 20]
    ],
    scenario_2: [
        ['direction', 'FORWARD'],
        ['status', 'POWER_ON'],
        ['set_speed', 6],
        ['wait', 30],
        ['set_speed', 10],
        ['wait', 100],
        ['set_speed', 6],
        ['wait', 30],
        ['set_speed', 0],
        ['status', 'POWER_OFF'],
        ['wait', 30],
        ['direction', 'BACKWARD'],
        ['status', 'POWER_ON'],
        ['set_speed', 6],
        ['wait', 30],
        ['set_speed', 10],
        ['wait', 50],
        ['set_speed', 6],
        ['wait', 30],
        ['set_speed', 0],
        ['status', 'POWER_OFF'],
        ['wait', 30],
        ['direction', 'FORWARD'],
        ['status', 'POWER_ON'],
        ['set_speed', 6],
        ['wait', 30],
        ['set_speed', 10],
        ['wait', 100],
        ['set_speed', 6],
        ['wait', 30],
        ['set_speed', 0],
        ['status', 'POWER_OFF'],
        ['wait', 20],
        ['direction', 'BACKWARD'],
        ['status', 'POWER_ON'],
        ['set_speed', 6],
        ['wait', 30],
        ['set_speed', 10],
        ['wait', 150],
        ['set_speed', 6],
        ['wait', 30],
        ['set_speed', 0],
        ['status', 'POWER_OFF'],
        ['wait', 30]
    ]
};

// Export for use in modules
export default scenarios;

// Or for CommonJS
// module.exports = scenarios;