# Resolution definitions (width, height) in pixels
RESOLUTION_STANDARD_QQVGA        = (160, 120)
RESOLUTION_STANDARD_QVGA         = (320, 240)
RESOLUTION_STANDARD_VGA          = (640, 480)
RESOLUTION_STANDARD_SVGA         = (800, 600)
RESOLUTION_STANDARD_XGA          = (1024, 768)
RESOLUTION_STANDARD_UXGA         = (1600, 1200)
RESOLUTION_WIDESCREEN_WXGA       = (1280, 800)
RESOLUTION_WIDESCREEN_HD         = (1280, 720)
RESOLUTION_WIDESCREEN_HD_PLUS    = (1600, 900)
RESOLUTION_WIDESCREEN_FHD        = (1920, 1080)
RESOLUTION_WIDESCREEN_WUXGA      = (1920, 1200)
RESOLUTION_QHD_2K                = (2560, 1440)
RESOLUTION_QHD_WQHD              = (2560, 1440)
RESOLUTION_QHD_DCI               = (2048, 1080)
RESOLUTION_ULTRAWIDE_UWHD        = (2560, 1080)
RESOLUTION_ULTRAWIDE_UWQHD       = (3440, 1440)
RESOLUTION_ULTRAWIDE_5K          = (5120, 2160)
RESOLUTION_UHD_4K                = (3840, 2160)
RESOLUTION_UHD_DCI               = (4096, 2160)
RESOLUTION_HIGH_5K               = (5120, 2880)
RESOLUTION_HIGH_8K               = (7680, 4320)

# Video Format Constants (Picamera2 / FFmpeg / OpenCV)
VIDEO_FORMAT_RGB332         = {"picamera": "RGB332",    "ffmpeg": None,             "opencv": None}
VIDEO_FORMAT_RGB444         = {"picamera": "RGB444",    "ffmpeg": "rgb444le",       "opencv": None}
VIDEO_FORMAT_RGB555         = {"picamera": "RGB555",    "ffmpeg": "rgb555le",       "opencv": None}
VIDEO_FORMAT_RGB565         = {"picamera": "RGB565",    "ffmpeg": "rgb565le",       "opencv": None}
VIDEO_FORMAT_RGB888         = {"picamera": "RGB888",    "ffmpeg": "rgb24",          "opencv": "RGB"}
VIDEO_FORMAT_ARGB8888       = {"picamera": "ARGB8888",  "ffmpeg": "argb",           "opencv": "ARGB"}
VIDEO_FORMAT_RGBA8888       = {"picamera": "RGBA8888",  "ffmpeg": "rgba",           "opencv": "RGBA"}
VIDEO_FORMAT_BGRA8888       = {"picamera": "BGRA8888",  "ffmpeg": "bgra",           "opencv": "BGRA"}
VIDEO_FORMAT_YUYV           = {"picamera": "YUYV",      "ffmpeg": "yuyv422",        "opencv": "YUYV"}
VIDEO_FORMAT_UYVY           = {"picamera": "UYVY",      "ffmpeg": "uyvy422",        "opencv": "UYVY"}
VIDEO_FORMAT_VYUY           = {"picamera": "VYUY",      "ffmpeg": None,             "opencv": None}
VIDEO_FORMAT_YVYU           = {"picamera": "YVYU",      "ffmpeg": "yvyu422",        "opencv": "YVYU"}
VIDEO_FORMAT_YUV420         = {"picamera": "YUV420",    "ffmpeg": "yuv420p",        "opencv": "YUV420"}
VIDEO_FORMAT_YUV422         = {"picamera": "YUV422",    "ffmpeg": "yuv422p",        "opencv": "YUV422"}
VIDEO_FORMAT_YUV444         = {"picamera": "YUV444",    "ffmpeg": "yuv444p",        "opencv": "YUV444"}
VIDEO_FORMAT_NV12           = {"picamera": "NV12",      "ffmpeg": "nv12",           "opencv": "NV12"}
VIDEO_FORMAT_NV21           = {"picamera": "NV21",      "ffmpeg": "nv21",           "opencv": "NV21"}
VIDEO_FORMAT_GRAY8          = {"picamera": "GRAY8",     "ffmpeg": "gray",           "opencv": "GRAY"}
VIDEO_FORMAT_GRAY10         = {"picamera": "GRAY10",    "ffmpeg": None,             "opencv": None}
VIDEO_FORMAT_GRAY12         = {"picamera": "GRAY12",    "ffmpeg": None,             "opencv": None}
VIDEO_FORMAT_BAYER_BGGR8    = {"picamera": "BGGR8",     "ffmpeg": "bayer_bggr8",    "opencv": None}
VIDEO_FORMAT_BAYER_GBRG8    = {"picamera": "GBRG8",     "ffmpeg": "bayer_gbrg8",    "opencv": None}
VIDEO_FORMAT_BAYER_GRBG8    = {"picamera": "GRBG8",     "ffmpeg": "bayer_grbg8",    "opencv": None}
VIDEO_FORMAT_BAYER_RGGB8    = {"picamera": "RGGB8",     "ffmpeg": "bayer_rggb8",    "opencv": None}
VIDEO_FORMAT_BAYER_BGGR10   = {"picamera": "BGGR10",    "ffmpeg": "bayer_bggr10",   "opencv": None}
VIDEO_FORMAT_BAYER_RGGB10   = {"picamera": "RGGB10",    "ffmpeg": "bayer_rggb10",   "opencv": None}
VIDEO_FORMAT_MJPEG          = {"picamera": "MJPEG",     "ffmpeg": "mjpeg",          "opencv": "MJPG"}
VIDEO_FORMAT_H264           = {"picamera": "H264",      "ffmpeg": "h264",           "opencv": "H264"}
VIDEO_FORMAT_H265           = {"picamera": "H265",      "ffmpeg": "hevc",           "opencv": "HEVC"}
VIDEO_FORMAT_AV1            = {"picamera": "AV1",       "ffmpeg": "av1",            "opencv": "AV01"}
